version: "3.8"

services:
  backend:
    build: .
    container_name: nest_backend
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - AMQP_URL=amqp://rabbitmq
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: express_frontend
    depends_on:
      - backend
    ports:
      - "3001:3001"
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq_service
    ports:
      - "5672:5672"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
